# Generated by Django 2.0.5 on 2018-06-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20170919_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='provider',
        ),
        migrations.DeleteModel(
            name='DonationProvider',
        ),
    ]
